export default {
  ENGLISH: 'English',
  LANGUAGE: 'Language',
  SYNCDATA: 'Sync Data',
  RFIDSETTING: 'RFID Setting',
  ALERTS: 'Alerts',
  DEVICEDETAILS: 'Device details',
  ADVANCEDSETTINGS: 'Advanced settings',
  SETTINGS: 'Settings',
  FULLCYCLESOLUTION: 'Full Cycle Solution',
  TRANSACTIONS: 'TRANSACTIONS',
  ADDEDITITEMS: 'ADD/EDIT ITEMS',
  QUICKSCAN: 'QUICK SCAN',
  CLEAN: 'Clean',
  SUPPLYTOLOCAITON: 'Supply To Location',
  SOIL: 'Soil',
  STARTSCAN: 'START SCAN',
};
