export default {
  ENGLISH: 'Inglês',
  LANGUAGE: 'Língua',
  SYNCDATA: 'sincronizar dados',
  RFIDSETTING: 'RFID Contexto',
  ALERTS: 'Alertas',
  DEVICEDETAILS: 'Detalhes do dispositivo',
  ADVANCEDSETTINGS: 'Configurações avançadas',
  SETTINGS: 'Definições',
  SETTINGS: 'Contexto',
  FULLCYCLESOLUTION: 'Solução de ciclo completo',
  TRANSACTIONS: 'TRANSAÇÕES',
  ADDEDITITEMS: 'ADICIONAR/EDITAR ITENS',
  QUICKSCAN: 'ESCANEAMENTO RÁPIDO',
  CLEAN: 'Limpar',
  SUPPLYTOLOCAITON: 'Fornecimento para o local',
  SOIL: 'Solo',
  STARTSCAN: 'INICIA ESCANEAMENTO',
};
